clc;
clear all;

a=load('c.txt');
a=[a(:,2) a(:,3) a(:,4)];

plot3(a(:,1), a(:,2), a(:,3), '--gs',...
    'LineStyle','none','Marker','+',...
    'MarkerSize',15.0,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor',[0.5,0.5,0.5]);